import { NextRequest, NextResponse } from "next/server";
import { detectCommitments } from "@/lib/commitment/detector";

export const dynamic = "force-dynamic";

/**
 * POST /api/emails/local-analyze
 *
 * Local (no-LLM) inbox intelligence analysis.
 * Detects research signals, commitments, and hypothesis-relevant evidence
 * using deterministic text analysis.
 *
 * Body: { emails: [{ id, from, subject, preview, date, attachmentCount }] }
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const emails: any[] = body.emails || [];
    if (emails.length === 0) {
      return NextResponse.json({ error: "No emails provided" }, { status: 400 });
    }

    // ─── Research Signals ────────────────────────────────────────────
    const RESEARCH_TERMS = [
      "study", "trial", "data", "results", "outcome", "efficacy", "safety",
      "response rate", "survival", "remission", "adherence", "biomarker",
      "combination", "phase", "endpoint", "statistically significant",
      "p-value", "confidence interval", "hazard ratio", "NNT", "evidence",
      "RCT", "meta-analysis", "systematic review", "observational",
    ];
    const researchSignals: string[] = [];
    for (const email of emails.slice(0, 25)) {
      const text = `${email.subject || ""} ${email.preview || ""}`.toLowerCase();
      const matches = RESEARCH_TERMS.filter(t => text.includes(t));
      if (matches.length >= 2) {
        researchSignals.push(
          `**${email.subject || "(no subject)"}** (from ${email.from || "unknown"}) — ` +
          `contains research-relevant terms: ${matches.slice(0, 5).join(", ")}` +
          (email.attachmentCount > 0 ? `. Has ${email.attachmentCount} attachment(s) — may contain data.` : "")
        );
      }
    }

    // ─── Commitments ─────────────────────────────────────────────────
    const COMMITMENT_PATTERNS = [
      { regex: /\bby (friday|monday|tuesday|wednesday|thursday|end of week|eow)\b/gi, type: "deadline" },
      { regex: /\b(asap|urgent|immediately|right away)\b/gi, type: "urgent deadline" },
      { regex: /\b(please (prepare|send|review|update|create|draft|complete|schedule|provide|analyze|summarize))\b/gi, type: "action request" },
      { regex: /\b(i will|i'll|commit|promise|guarantee)\b/gi, type: "outgoing commitment" },
      { regex: /\b(follow up|followup|check back|circle back)\b/gi, type: "follow-up" },
      { regex: /\b(need|require|must have|deliver)\b/gi, type: "requirement" },
      { regex: /\b\d{1,2}\/\d{1,2}\/\d{2,4}\b|\b\d{4}-\d{2}-\d{2}\b/g, type: "explicit date" },
    ];
    const commitments: string[] = [];
    for (const email of emails.slice(0, 25)) {
      const text = `${email.subject || ""} ${email.preview || ""}`;
      for (const { regex, type } of COMMITMENT_PATTERNS) {
        const matches = text.match(regex);
        if (matches) {
          for (const match of matches.slice(0, 2)) {
            commitments.push(
              `**${email.subject || "(no subject)"}** (from ${email.from || "unknown"}) — ` +
              `${type}: "${match}"`
            );
          }
        }
      }
    }

    // ─── Hypothesis-Relevant Evidence ────────────────────────────────
    const HYPOTHESIS_TERMS = [
      "formulary", "P&T committee", "coverage", "access", "formulary review",
      "prescribing", "adoption", "initiation", "switch", "discontinue",
      "barrier", "obstacle", "challenge", "objection", "concern",
      "guideline", "recommendation", "protocol", "pathway",
      "competitive", "competitor", "alternative", "vs", "versus",
      "cost", "reimbursement", "prior auth", "prior authorization",
      "patient population", "treatment-naive", "treatment-experienced",
    ];
    const hypothesisEvidence: string[] = [];
    for (const email of emails.slice(0, 25)) {
      const text = `${email.subject || ""} ${email.preview || ""}`.toLowerCase();
      const matches = HYPOTHESIS_TERMS.filter(t => text.includes(t.toLowerCase()));
      if (matches.length >= 1) {
        hypothesisEvidence.push(
          `**${email.subject || "(no subject)"}** (from ${email.from || "unknown"}) — ` +
          `relevant terms: ${matches.slice(0, 4).join(", ")}`
        );
      }
    }

    // ─── Build Report ────────────────────────────────────────────────
    const report = `## Research Signals\n\n${researchSignals.length > 0 ? researchSignals.map(s => `- ${s}`).join("\n") : "None detected."}\n\n## Commitments\n\n${commitments.length > 0 ? commitments.map(c => `- ${c}`).join("\n") : "None detected."}\n\n## Hypothesis-Relevant Evidence\n\n${hypothesisEvidence.length > 0 ? hypothesisEvidence.map(e => `- ${e}`).join("\n") : "None detected."}\n\n---\n*Generated by local deterministic analysis (no LLM required)*`;

    return NextResponse.json({
      content: report,
      provider: "local",
      stats: {
        emailsAnalyzed: Math.min(emails.length, 25),
        researchSignals: researchSignals.length,
        commitments: commitments.length,
        hypothesisEvidence: hypothesisEvidence.length,
      },
    });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
