import { withFoundryVoice } from "@/lib/foundry-voice";

export interface GileadFunction {
  id: string;
  name: string;
  category: string;
  description: string;
  systemPrompt: string;
  userPromptTemplate: string;
  icon: string;
}

export const GILEAD_FUNCTIONS: GileadFunction[] = [
  // Deal Pipeline Management
  {
    id: "deal-prioritization",
    name: "Deal Prioritization Matrix",
    category: "Pipeline",
    description: "Rank open deals by revenue potential, close probability, and urgency",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a Gilead Sciences sales strategy assistant. Analyze deals and rank them by revenue potential, probability of close, and urgency. Return a prioritized list with reasoning."),
    userPromptTemplate: "Analyze and prioritize these open deals:\n\n{deals}\n\nRank by: 1) Revenue potential 2) Close probability 3) Urgency. Return as a ranked table.",
    icon: "📊",
  },
  {
    id: "pipeline-forecast",
    name: "Quarterly Pipeline Forecast",
    category: "Pipeline",
    description: "Generate revenue forecast from current pipeline data",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a pharmaceutical sales forecasting assistant for Gilead Sciences. Generate accurate quarterly revenue forecasts based on pipeline data, historical close rates, and deal stages."),
    userPromptTemplate: "Generate a quarterly forecast from this pipeline:\n\n{pipeline}\n\nInclude: expected revenue, best case, worst case, and confidence intervals.",
    icon: "📈",
  },
  {
    id: "deal-stall-detector",
    name: "Stalled Deal Detector",
    category: "Pipeline",
    description: "Identify deals that have stalled and recommend re-engagement strategies",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a sales pipeline health assistant for Gilead Sciences. Identify stalled deals and provide specific re-engagement strategies for each."),
    userPromptTemplate: "Analyze these deals for stall indicators (no activity >14 days, stage not advancing, etc.):\n\n{deals}\n\nFor each stalled deal, provide: 1) Stall reason 2) Re-engagement action 3) Recommended timeline.",
    icon: "⚠️",
  },
  {
    id: "whitespace-analysis",
    name: "Territory Whitespace Analysis",
    category: "Pipeline",
    description: "Identify untapped accounts and prescribing potential in your territory",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a pharmaceutical territory analysis assistant for Gilead Sciences. Identify whitespace opportunities by analyzing prescriber data, competitor presence, and demographic information."),
    userPromptTemplate: "Analyze this territory for whitespace opportunities:\n\nTerritory: {territory}\nCurrent accounts: {accounts}\n\nIdentify: 1) Untapped high-value accounts 2) Under-penetrated specialties 3) Geographic gaps.",
    icon: "🗺️",
  },

  // Email Intelligence
  {
    id: "email-triage",
    name: "Smart Email Triage",
    category: "Email",
    description: "Automatically categorize and prioritize incoming emails by revenue impact",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a Gilead Sciences sales email triage assistant. Categorize emails by type (customer inquiry, HCP communication, internal, regulatory, opportunity) and assign priority based on revenue impact and urgency."),
    userPromptTemplate: "Triage these emails:\n\n{emails}\n\nFor each: 1) Category 2) Priority (High/Medium/Low) 3) Revenue impact 4) Recommended response time 5) Suggested action.",
    icon: "📧",
  },
  {
    id: "email-sentiment",
    name: "Customer Sentiment Analysis",
    category: "Email",
    description: "Analyze email tone and sentiment to gauge customer satisfaction",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a customer relationship assistant for Gilead Sciences. Analyze email sentiment from healthcare providers, pharmacists, and procurement officers. Identify satisfaction levels, concerns, and buying signals."),
    userPromptTemplate: "Analyze the sentiment and tone of this email:\n\nFrom: {sender}\nSubject: {subject}\nBody: {body}\n\nProvide: 1) Overall sentiment (-5 to +5) 2) Key emotions detected 3) Buying signals 4) Concerns 5) Recommended response approach.",
    icon: "😊",
  },
  {
    id: "follow-up-timing",
    name: "Optimal Follow-up Timing",
    category: "Email",
    description: "Determine the best time and channel to follow up with each contact",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a sales cadence assistant for Gilead Sciences. Determine optimal follow-up timing based on contact role, engagement history, deal stage, and communication preferences."),
    userPromptTemplate: "Determine the optimal follow-up plan for:\n\nContact: {contact}\nRole: {role}\nLast interaction: {lastInteraction}\nDeal stage: {dealStage}\n\nProvide: 1) Best day/time to follow up 2) Channel (email/phone/in-person) 3) Message angle 4) Cadence schedule.",
    icon: "⏰",
  },
  {
    id: "email-draft",
    name: "Personalized Email Draft",
    category: "Email",
    description: "Generate personalized emails tailored to HCP specialties and interests",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a Gilead Sciences sales communication assistant. Draft personalized, compliant emails for healthcare providers. Ensure FDA-compliant language, include relevant clinical data, and match the HCP's communication style."),
    userPromptTemplate: "Draft a personalized email to:\n\nRecipient: {recipient}\nRole: {role}\nSpecialty: {specialty}\nProduct: {product}\nObjective: {objective}\nPrevious interactions: {history}\n\nKeep it under 200 words, professional, and include a clear CTA.",
    icon: "✍️",
  },
  {
    id: "objection-response",
    name: "Objection Handling Response",
    category: "Email",
    description: "Generate responses to common sales objections with clinical evidence",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a Gilead Sciences sales objection handling assistant. Generate evidence-based responses to common objections about Gilead products (Biktarvy, Descovy, Trodelvy, Yescarta, etc.). Use clinical trial data and HEOR evidence."),
    userPromptTemplate: "Generate a response to this objection:\n\nObjection: {objection}\nProduct: {product}\nCustomer type: {customerType}\n\nProvide: 1) Acknowledgment 2) Evidence-based counter 3) Clinical data reference 4) Next step suggestion.",
    icon: "🛡️",
  },

  // Account Management
  {
    id: "account-plan",
    name: "Strategic Account Plan",
    category: "Accounts",
    description: "Generate a comprehensive account plan for key hospital systems",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a strategic account planning assistant for Gilead Sciences. Create comprehensive account plans for hospital systems, IDNs, and specialty pharmacies. Include stakeholder maps, formulary status, and growth opportunities."),
    userPromptTemplate: "Create a strategic account plan for:\n\nAccount: {account}\nType: {accountType}\nCurrent products: {currentProducts}\nAnnual revenue: {revenue}\nKey contacts: {contacts}\n\nInclude: 1) Stakeholder map 2) Formulary status 3) Growth opportunities 4) 90-day action plan 5) Risk assessment.",
    icon: "🏢",
  },
  {
    id: "stakeholder-map",
    name: "Stakeholder Mapping",
    category: "Accounts",
    description: "Map decision-makers, influencers, and blockers in an account",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a stakeholder mapping assistant for Gilead Sciences. Map the decision-making hierarchy in healthcare organizations, identifying champions, influencers, blockers, and decision-makers."),
    userPromptTemplate: "Map the stakeholders for:\n\nAccount: {account}\nKnown contacts: {contacts}\n\nFor each stakeholder: 1) Role 2) Influence level (1-5) 3) Attitude (Champion/Supporter/Neutral/Skeptic/Blocker) 4) Key motivators 5) Engagement strategy.",
    icon: "🕸️",
  },
  {
    id: "formulary-strategy",
    name: "Formulary Strategy",
    category: "Accounts",
    description: "Develop formulary approval strategies for Gilead products",
    systemPrompt: withFoundryVoice("sales-strategy", "You are a formulary strategy assistant for Gilead Sciences. Develop strategies for P&T committee presentations, formulary submissions, and tier placement negotiations for Gilead's portfolio."),
    userPromptTemplate: "Develop a formulary strategy for:\n\nProduct: {product}\nAccount: {account}\nCurrent formulary status: {status}\nCompetitor products on formulary: {competitors}\n\nInclude: 1) P&T presentation outline 2) Clinical evidence package 3) HEOR data 4) Pricing strategy 5) Timeline.",
    icon: "📋",
  },
  {
    id: "account-health-score",
    name: "Account Health Score",
    category: "Accounts",
    description: "Score account health based on engagement, revenue, and risk factors",
    systemPrompt: withFoundryVoice("sales-strategy", "You are an account health scoring assistant for Gilead Sciences. Calculate account health scores based on revenue trends, engagement frequency, formulary status, competitive threats, and payment history."),
    userPromptTemplate: "Calculate an account health score for:\n\nAccount: {account}\nRevenue trend (6mo): {revenueTrend}\nEngagement frequency: {engagement}\nFormulary status: {formulary}\nCompetitor activity: {competitors}\nPayment history: {payments}\n\nProvide: 1) Health score (0-100) 2) Trend (improving/stable/declining) 3) Risk factors 4) Recommended actions.",
    icon: "❤️",
  },

  // Clinical & Product Intelligence
  {
    id: "clinical-data-summary",
    name: "Clinical Trial Data Summary",
    category: "Clinical",
    description: "Summarize clinical trial results for sales conversations",
    systemPrompt: withFoundryVoice("clinical", "You are a clinical data summarization assistant for Gilead Sciences. Summarize clinical trial results into sales-ready talking points. Focus on efficacy, safety, and differentiation vs competitors. Ensure all claims are FDA-compliant."),
    userPromptTemplate: "Summarize this clinical trial data for a sales conversation:\n\nProduct: {product}\nTrial: {trial}\nData: {data}\n\nProvide: 1) Key efficacy findings 2) Safety profile 3) Differentiation vs competitors 4) Sales talking points 5) FDA-compliant claims.",
    icon: "🔬",
  },
  {
    id: "competitive-intelligence",
    name: "Competitive Intelligence Brief",
    category: "Clinical",
    description: "Generate competitive intelligence on rival products and strategies",
    systemPrompt: withFoundryVoice("clinical", "You are a competitive intelligence assistant for Gilead Sciences. Analyze competitor products, clinical data, market positioning, and sales strategies. Provide actionable intelligence for field sales teams."),
    userPromptTemplate: "Generate a competitive intelligence brief:\n\nCompetitor: {competitor}\nProduct: {competitorProduct}\nOur product: {ourProduct}\n\nInclude: 1) Head-to-head clinical comparison 2) Market share data 3) Pricing comparison 4) Competitor sales strategy 5) Our counter-positioning.",
    icon: "🔍",
  },
  {
    id: "product-positioning",
    name: "Product Positioning Statement",
    category: "Clinical",
    description: "Create tailored product positioning for different HCP specialties",
    systemPrompt: withFoundryVoice("clinical", "You are a product positioning assistant for Gilead Sciences. Create tailored positioning statements for different HCP specialties (ID, oncology, rheumatology, hepatology, etc.). Ensure messaging is FDA-compliant and clinically accurate."),
    userPromptTemplate: "Create a product positioning statement for:\n\nProduct: {product}\nTarget specialty: {specialty}\nKey clinical benefit: {benefit}\nCompetitor alternative: {competitor}\n\nProvide: 1) Positioning statement 2) Key messages (3) 3) Supporting evidence 4) Elevator pitch 5) FAQ responses.",
    icon: "🎯",
  },
  {
    id: "heor-value-story",
    name: "HEOR Value Story",
    category: "Clinical",
    description: "Build health economics and outcomes research value stories",
    systemPrompt: withFoundryVoice("clinical", "You are a health economics assistant for Gilead Sciences. Create compelling HEOR value stories that demonstrate the economic value of Gilead products to payers, IDNs, and pharmacy directors."),
    userPromptTemplate: "Create an HEOR value story for:\n\nProduct: {product}\nTarget audience: {audience}\nBudget impact data: {budget}\nCost-effectiveness data: {ceData}\n\nInclude: 1) Economic value proposition 2) Budget impact summary 3) Cost per QALY 4) Real-world evidence 5) Payer talking points.",
    icon: "💰",
  },

  // Sales Planning & Strategy
  {
    id: "call-plan",
    name: "Daily Call Plan",
    category: "Planning",
    description: "Optimize daily call routes and visit priorities",
    systemPrompt: withFoundryVoice("planning", "You are a sales call planning assistant for Gilead Sciences. Optimize daily call routes, prioritize visits by revenue potential and urgency, and suggest discussion topics for each visit."),
    userPromptTemplate: "Create an optimized daily call plan for:\n\nDate: {date}\nTerritory: {territory}\nAccounts to visit: {accounts}\nPriorities: {priorities}\n\nProvide: 1) Optimized route order 2) Visit duration estimates 3) Discussion topics per visit 4) Materials to bring 5) Objectives per visit.",
    icon: "🗓️",
  },
  {
    id: "quarterly-plan",
    name: "Quarterly Sales Plan",
    category: "Planning",
    description: "Generate a comprehensive quarterly sales plan with goals and KPIs",
    systemPrompt: withFoundryVoice("planning", "You are a quarterly sales planning assistant for Gilead Sciences. Create comprehensive quarterly plans with SMART goals, KPIs, territory strategies, and resource allocation recommendations."),
    userPromptTemplate: "Create a quarterly sales plan for:\n\nSales rep: {rep}\nTerritory: {territory}\nQuota: {quota}\nCurrent pipeline: {pipeline}\nHistorical performance: {history}\n\nInclude: 1) SMART goals 2) KPIs 3) Territory strategy 4) Account priorities 5) Activity targets 6) Resource needs.",
    icon: "📅",
  },
  {
    id: "budget-allocation",
    name: "Territory Budget Allocation",
    category: "Planning",
    description: "Optimize territory budget across activities, samples, and events",
    systemPrompt: withFoundryVoice("planning", "You are a sales budget optimization assistant for Gilead Sciences. Recommend optimal budget allocation across speaker programs, sample drops, conference attendance, and customer meals to maximize ROI."),
    userPromptTemplate: "Optimize budget allocation for:\n\nTerritory: {territory}\nTotal budget: {budget}\nHistorical spend: {history}\nROI by activity: {roi}\n\nProvide: 1) Recommended allocation 2) Expected ROI per category 3) Risk assessment 4) Compliance considerations.",
    icon: "💵",
  },
  {
    id: "goal-setting",
    name: "SMART Goal Generator",
    category: "Planning",
    description: "Generate SMART goals based on territory potential and historical data",
    systemPrompt: withFoundryVoice("planning", "You are a sales goal-setting assistant for Gilead Sciences. Generate SMART (Specific, Measurable, Achievable, Relevant, Time-bound) goals based on territory potential, historical performance, and market conditions."),
    userPromptTemplate: "Generate SMART goals for:\n\nSales rep: {rep}\nTerritory: {territory}\nPrior year performance: {priorYear}\nMarket growth: {marketGrowth}\nNew products: {newProducts}\n\nCreate 5-7 SMART goals covering: revenue, new accounts, product mix, call activity, and professional development.",
    icon: "🎯",
  },

  // Customer Engagement
  {
    id: "speaker-program",
    name: "Speaker Program Planner",
    category: "Engagement",
    description: "Plan compliant speaker programs with topic and audience recommendations",
    systemPrompt: withFoundryVoice("engagement", "You are a speaker program planning assistant for Gilead Sciences. Recommend compliant speaker programs including topic selection, target audience, venue, and promotional strategy. Ensure all recommendations comply with Sunshine Act and PhRMA guidelines."),
    userPromptTemplate: "Plan a speaker program for:\n\nProduct: {product}\nTherapeutic area: {therapeuticArea}\nTarget audience: {audience}\nGeography: {geography}\nBudget: {budget}\n\nInclude: 1) Recommended topic 2) Speaker qualifications 3) Venue suggestions 4) Promotional plan 5) Compliance checklist 6) Expected attendance 7) ROI projection.",
    icon: "🎤",
  },
  {
    id: "lunch-learn",
    name: "Lunch & Learn Organizer",
    category: "Engagement",
    description: "Organize lunch and learn events with personalized content",
    systemPrompt: withFoundryVoice("engagement", "You are a lunch and learn planning assistant for Gilead Sciences. Help organize impactful lunch and learn sessions at HCP offices, including content recommendations, logistics, and follow-up plans."),
    userPromptTemplate: "Plan a lunch and learn for:\n\nAccount: {account}\nProduct: {product}\nAttendees: {attendees}\nDate: {date}\n\nInclude: 1) Presentation topic 2) Key clinical messages 3) Materials needed 4) Food logistics 5) Follow-up plan 6) Compliance notes.",
    icon: "🍽️",
  },
  {
    id: "conference-strategy",
    name: "Conference Engagement Strategy",
    category: "Engagement",
    description: "Plan conference engagement with target HCPs and booth strategy",
    systemPrompt: withFoundryVoice("engagement", "You are a conference strategy assistant for Gilead Sciences. Plan conference engagement including target HCP meetings, booth strategy, scientific session attendance, and post-conference follow-up."),
    userPromptTemplate: "Create a conference engagement strategy for:\n\nConference: {conference}\nDates: {dates}\nTarget HCPs: {hcps}\nProducts to highlight: {products}\nBooth location: {booth}\n\nInclude: 1) Pre-conference outreach plan 2) Target meeting schedule 3) Booth strategy 4) Session attendance plan 5) Post-conference follow-up 6) ROI metrics.",
    icon: "🎪",
  },
  {
    id: "patient-support",
    name: "Patient Support Program Guide",
    category: "Engagement",
    description: "Generate patient support and access program recommendations",
    systemPrompt: withFoundryVoice("engagement", "You are a patient access assistant for Gilead Sciences. Recommend appropriate patient support programs, co-pay assistance, and access resources based on patient insurance status and product."),
    userPromptTemplate: "Recommend patient support options for:\n\nProduct: {product}\nPatient insurance type: {insurance}\nPatient financial situation: {financial}\nGeography: {geography}\n\nInclude: 1) Eligible programs 2) Co-pay card info 3) PAP enrollment steps 4) Foundation support 5) Pharmacy network recommendations.",
    icon: "🤝",
  },

  // Analytics & Reporting
  {
    id: "sales-trend-analysis",
    name: "Sales Trend Analysis",
    category: "Analytics",
    description: "Analyze prescription and sales trends with actionable insights",
    systemPrompt: withFoundryVoice("analytics", "You are a sales analytics assistant for Gilead Sciences. Analyze prescription data, sales trends, and market share movements. Provide actionable insights for sales reps to adjust their strategies."),
    userPromptTemplate: "Analyze these sales trends:\n\nProduct: {product}\nTime period: {period}\nRx data: {rxData}\nMarket share: {marketShare}\nCompetitor activity: {competitors}\n\nProvide: 1) Trend summary 2) Key drivers 3) Anomalies 4) Market share analysis 5) Recommended actions 6) 30-day focus areas.",
    icon: "📉",
  },
  {
    id: "kpi-dashboard",
    name: "KPI Dashboard Summary",
    category: "Analytics",
    description: "Generate a KPI summary with performance vs quota and trends",
    systemPrompt: withFoundryVoice("analytics", "You are a sales KPI assistant for Gilead Sciences. Generate comprehensive KPI summaries comparing actual performance to quota, highlighting areas of concern, and recommending corrective actions."),
    userPromptTemplate: "Generate a KPI summary for:\n\nSales rep: {rep}\nPeriod: {period}\nQuota: {quota}\nActual: {actual}\nCall metrics: {calls}\nPipeline: {pipeline}\n\nProvide: 1) Performance vs quota 2) Key metric highlights 3) Areas of concern 4) Corrective actions 5) 30-day priorities.",
    icon: "📋",
  },
  {
    id: "roi-analysis",
    name: "Activity ROI Analysis",
    category: "Analytics",
    description: "Calculate ROI for sales activities and recommend reallocation",
    systemPrompt: withFoundryVoice("analytics", "You are a sales ROI analysis assistant for Gilead Sciences. Calculate return on investment for various sales activities (calls, programs, conferences, samples) and recommend budget reallocation."),
    userPromptTemplate: "Calculate ROI for these activities:\n\nActivities: {activities}\nCost per activity: {costs}\nRevenue attributed: {revenue}\nTime invested: {time}\n\nProvide: 1) ROI per activity 2) Most/least efficient activities 3) Reallocation recommendations 4) Time optimization suggestions.",
    icon: "💱",
  },
  {
    id: "prescriber-analysis",
    name: "Top Prescriber Analysis",
    category: "Analytics",
    description: "Identify and analyze top prescribers with growth potential",
    systemPrompt: withFoundryVoice("analytics", "You are a prescriber analytics assistant for Gilead Sciences. Identify top prescribers, analyze prescribing patterns, and recommend engagement strategies to grow share of voice."),
    userPromptTemplate: "Analyze top prescribers in this territory:\n\nTerritory: {territory}\nPrescriber data: {prescribers}\nProduct: {product}\n\nProvide: 1) Top 20 prescribers by volume 2) Growth potential scoring 3) Share of voice analysis 4) Engagement priority ranking 5) Cross-selling opportunities.",
    icon: "👨‍⚕️",
  },

  // Compliance & Regulatory
  {
    id: "compliance-check",
    name: "Communication Compliance Check",
    category: "Compliance",
    description: "Verify sales communications meet FDA and PhRMA guidelines",
    systemPrompt: withFoundryVoice("compliance", "You are a pharmaceutical compliance assistant for Gilead Sciences. Review sales communications for FDA compliance, PhRMA Code adherence, and Sunshine Act implications. Flag any potential violations."),
    userPromptTemplate: "Review this communication for compliance:\n\nType: {type}\nContent: {content}\nProduct: {product}\nAudience: {audience}\n\nCheck: 1) FDA on-label claims 2) Fair balance 3) PhRMA Code compliance 4) Sunshine Act reporting needs 5) Required disclaimers 6) Risk of off-label promotion.",
    icon: "⚖️",
  },
  {
    id: "sample-tracking",
    name: "Sample Inventory Optimization",
    category: "Compliance",
    description: "Optimize sample allocation and ensure PDMA compliance",
    systemPrompt: withFoundryVoice("compliance", "You are a sample management assistant for Gilead Sciences. Optimize sample allocation across territories, ensure PDMA compliance, and recommend sample drop schedules based on prescriber needs."),
    userPromptTemplate: "Optimize sample allocation for:\n\nTerritory: {territory}\nCurrent inventory: {inventory}\nTop prescribers: {prescribers}\nHistorical usage: {usage}\n\nProvide: 1) Allocation recommendations 2) Drop schedule 3) PDMA compliance checklist 4) Storage requirements 5) Expiration management.",
    icon: "📦",
  },
  {
    id: "adverse-event-screen",
    name: "Adverse Event Screening",
    category: "Compliance",
    description: "Screen communications for adverse event reports requiring submission",
    systemPrompt: withFoundryVoice("compliance", "You are a pharmacovigilance assistant for Gilead Sciences. Screen sales communications for potential adverse event reports that require submission to Drug Safety. Flag any AE mentions immediately."),
    userPromptTemplate: "Screen this communication for adverse events:\n\nSource: {source}\nContent: {content}\nProduct: {product}\n\nIdentify: 1) Any adverse events mentioned 2) Product complaints 3) Medication errors 4) Required reporting actions 5) Timeframe for submission 6) Drug Safety contact reminder.",
    icon: "🚨",
  },
];

export const GILEAD_CATEGORIES = [
  "Pipeline",
  "Email",
  "Accounts",
  "Clinical",
  "Planning",
  "Engagement",
  "Analytics",
  "Compliance",
];
