/**
 * Key-providers registry — major platforms that issue API keys/tokens.
 *
 * Each entry records the platform's *documented, public* token-management URL
 * and the acquisition/revocation method. Most platforms do NOT expose a
 * programmatic "create API key" endpoint (this is a deliberate security
 * choice); for those, acquisition is `ui_playwright` — the agent navigates the
 * token page in the user's logged-in browser session and creates a key via the
 * UI, with honest logging when the flow cannot be completed.
 *
 * No endpoints are fabricated. Where `createEndpoint` is set, it is a
 * documented platform API. Where it is absent, the UI flow is used.
 */

import type { KeyPlatform } from "./key-types";

export const KEY_PLATFORMS: KeyPlatform[] = [
  {
    id: "huggingface",
    name: "Hugging Face",
    tokenPageUrl: "https://huggingface.co/settings/tokens",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "a[href*='tokens/new'], button:has-text('New token')",
    newNameFieldSelector: "input[name='name'], input[placeholder*='token name' i]",
    confirmButtonSelector: "button[type='submit']:has-text('Create'), button:has-text('Create token')",
    keyValueSelector: "code, input[readonly], textarea[readonly]",
    revokeButtonSelector: "button:has-text('Delete'), button:has-text('Revoke')",
    tags: ["ml", "models", "datasets", "inference"],
    description: "Access tokens for the Hugging Face Hub (models, datasets, inference API).",
  },
  {
    id: "github",
    name: "GitHub",
    tokenPageUrl: "https://github.com/settings/tokens",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "a[href*='new'], a:has-text('Generate new token')",
    newNameFieldSelector: "input[name='token_description']",
    confirmButtonSelector: "button:has-text('Generate token'), input[type='submit']",
    keyValueSelector: "#new-oauth-token, code, input[value^='ghp_'], input[value^='github_pat_']",
    revokeButtonSelector: "button:has-text('Delete'), input[value='Delete']",
    tags: ["code", "developer", "ci"],
    description: "Personal access tokens for the GitHub API.",
  },
  {
    id: "openai",
    name: "OpenAI",
    tokenPageUrl: "https://platform.openai.com/api-keys",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('Create new secret key'), button:has-text('Create secret key')",
    newNameFieldSelector: "input[placeholder*='name' i]",
    confirmButtonSelector: "button:has-text('Create secret key')",
    keyValueSelector: "input[readonly], code, [data-testid='secret-key']",
    revokeButtonSelector: "button:has-text('Revoke'), button:has-text('Delete')",
    tags: ["llm", "inference", "ai"],
    description: "Secret API keys for the OpenAI platform.",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    tokenPageUrl: "https://console.anthropic.com/settings/keys",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('Create Key')",
    newNameFieldSelector: "input[name='name'], input[placeholder*='name' i]",
    confirmButtonSelector: "button:has-text('Create Key')",
    keyValueSelector: "code, input[readonly], [data-testid='api-key']",
    revokeButtonSelector: "button:has-text('Revoke'), button:has-text('Delete')",
    tags: ["llm", "inference", "ai"],
    description: "API keys for the Anthropic Console (Claude).",
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    tokenPageUrl: "https://console.cloud.google.com/apis/credentials",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('Create credentials')",
    confirmButtonSelector: "button:has-text('Create')",
    keyValueSelector: "input[readonly], code",
    revokeButtonSelector: "button:has-text('Delete')",
    tags: ["cloud", "storage", "ai", "maps"],
    description: "API keys / service account keys for Google Cloud.",
  },
  {
    id: "replicate",
    name: "Replicate",
    tokenPageUrl: "https://replicate.com/account/api-tokens",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('Create token')",
    newNameFieldSelector: "input[placeholder*='name' i], input[name='name']",
    confirmButtonSelector: "button:has-text('Create token')",
    keyValueSelector: "code, input[readonly]",
    revokeButtonSelector: "button:has-text('Delete'), button:has-text('Revoke')",
    tags: ["ml", "inference", "ai"],
    description: "API tokens for Replicate model inference.",
  },
  {
    id: "together",
    name: "Together AI",
    tokenPageUrl: "https://api.together.ai/settings/api-keys",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('Create'), button:has-text('New key')",
    confirmButtonSelector: "button:has-text('Create')",
    keyValueSelector: "code, input[readonly]",
    revokeButtonSelector: "button:has-text('Delete'), button:has-text('Revoke')",
    tags: ["llm", "inference", "ai"],
    description: "API keys for Together AI inference.",
  },
  {
    id: "cohere",
    name: "Cohere",
    tokenPageUrl: "https://dashboard.cohere.com/api-keys",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('New key'), button:has-text('Create')",
    confirmButtonSelector: "button:has-text('Create')",
    keyValueSelector: "code, input[readonly]",
    revokeButtonSelector: "button:has-text('Delete'), button:has-text('Revoke')",
    tags: ["llm", "inference", "ai"],
    description: "API keys for Cohere.",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    tokenPageUrl: "https://console.mistral.ai/api-keys",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('Create new key'), button:has-text('Create')",
    confirmButtonSelector: "button:has-text('Create')",
    keyValueSelector: "code, input[readonly]",
    revokeButtonSelector: "button:has-text('Delete'), button:has-text('Revoke')",
    tags: ["llm", "inference", "ai"],
    description: "API keys for Mistral AI.",
  },
  {
    id: "groq",
    name: "Groq",
    tokenPageUrl: "https://console.groq.com/keys",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('Create'), button:has-text('New key')",
    confirmButtonSelector: "button:has-text('Create')",
    keyValueSelector: "code, input[readonly], span[title^='gsk_']",
    revokeButtonSelector: "button:has-text('Delete'), button:has-text('Revoke')",
    tags: ["llm", "inference", "ai"],
    description: "API keys for Groq inference.",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    tokenPageUrl: "https://www.perplexity.ai/settings/api",
    acquisition: "ui_playwright",
    revocation: "manual",
    supportsMultipleKeys: false,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('Generate'), button:has-text('Create')",
    confirmButtonSelector: "button:has-text('Generate')",
    keyValueSelector: "code, input[readonly]",
    tags: ["llm", "inference", "ai", "search"],
    description: "API keys for Perplexity Online API.",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    tokenPageUrl: "https://fireworks.ai/account/api-keys",
    acquisition: "ui_playwright",
    revocation: "ui_playwright",
    supportsMultipleKeys: true,
    defaultRotationDays: 90,
    createButtonSelector: "button:has-text('Create'), button:has-text('New key')",
    confirmButtonSelector: "button:has-text('Create')",
    keyValueSelector: "code, input[readonly]",
    revokeButtonSelector: "button:has-text('Delete'), button:has-text('Revoke')",
    tags: ["llm", "inference", "ai"],
    description: "API keys for Fireworks AI inference.",
  },
];

export function getKeyPlatformById(id: string): KeyPlatform | undefined {
  return KEY_PLATFORMS.find((p) => p.id === id);
}

export function listKeyPlatforms(): KeyPlatform[] {
  return KEY_PLATFORMS;
}
