"""YouTube script generator: conversation -> structured video script.

Converts a ChatSync Conversation into a structured YouTube video script with:
  - A catchy title and hook
  - A description and tags for YouTube SEO
  - Timed scenes (one per message) with visual, narration, and text overlay
  - An outro with call-to-action
  - A thumbnail suggestion

The generator is deterministic (no LLM required) so it works in any
deployment environment. When an OpenAI-compatible LLM endpoint is
configured (OPENAI_API_KEY / OPENAI_BASE_URL), it uses the LLM to produce
richer narration and titles; otherwise it falls back to templates.

Output is a YouTubeScript dataclass with a to_dict() method.
"""
from __future__ import annotations

import os
import re
import time
from dataclasses import dataclass, field, asdict
from typing import Optional

from models import Conversation


@dataclass
class Scene:
    scene_number: int
    start_time: str  # "0:30"
    end_time: str    # "1:15"
    visual: str      # description of what's on screen
    narration: str   # what the narrator says
    text_overlay: str  # text shown on screen

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class YouTubeScript:
    title: str
    hook: str
    description: str
    tags: list[str]
    source_title: str
    source: str
    message_count: int
    estimated_duration: str  # "5:30"
    scenes: list[Scene]
    outro: str
    thumbnail_suggestion: str
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        d = {
            "title": self.title,
            "hook": self.hook,
            "description": self.description,
            "tags": self.tags,
            "source_title": self.source_title,
            "source": self.source,
            "message_count": self.message_count,
            "estimated_duration": self.estimated_duration,
            "scenes": [s.to_dict() for s in self.scenes],
            "outro": self.outro,
            "thumbnail_suggestion": self.thumbnail_suggestion,
            "created_at": self.created_at,
        }
        return d


def _format_time(seconds: int) -> str:
    m, s = divmod(seconds, 60)
    return f"{m}:{s:02d}"


def _estimate_narration_duration(text: str) -> int:
    """Estimate narration duration in seconds (~150 words/min)."""
    words = len(text.split())
    return max(5, int(words / 2.5)) + 2  # +2s pause per scene


def _extract_keywords(text: str, max_kw: int = 8) -> list[str]:
    """Extract topical keywords for tags."""
    stopwords = {
        "the", "a", "an", "and", "or", "but", "is", "are", "was", "were",
        "to", "of", "in", "on", "at", "by", "for", "with", "about", "as",
        "this", "that", "it", "we", "they", "you", "i", "me", "my", "your",
        "how", "what", "why", "when", "where", "do", "does", "can", "will",
        "would", "should", "could", "if", "then", "so", "just", "like",
    }
    tokens = re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", text.lower())
    freq: dict[str, int] = {}
    for tok in tokens:
        if tok in stopwords or len(tok) < 3:
            continue
        freq[tok] = freq.get(tok, 0) + 1
    ranked = sorted(freq.items(), key=lambda x: (-x[1], x[0]))
    return [w for w, _ in ranked[:max_kw]]


def _make_title(conv: Conversation) -> str:
    """Generate a YouTube-optimized title from the conversation."""
    base = conv.title or "AI Conversation"
    # If the title is already short and punchy, use it.
    if len(base) <= 60:
        return base
    # Otherwise truncate at a word boundary.
    return base[:57].rsplit(" ", 1)[0] + "..."


def _make_hook(conv: Conversation) -> str:
    """Generate a 15-second hook from the first user message."""
    first_user = None
    for m in conv.messages:
        if m.role.value == "user" and m.content.strip():
            first_user = m.content.strip()
            break
    if not first_user:
        return "In this video, we dive into an fascinating AI conversation. Stay tuned for insights you won't want to miss."
    # Truncate to a punchy hook.
    hook = first_user[:200]
    if len(first_user) > 200:
        hook += "..."
    return f"Ever wondered: {hook} Let's break it down."


def _make_description(conv: Conversation) -> str:
    """Generate a YouTube description."""
    msg_count = len(conv.messages)
    keywords = _extract_keywords(
        " ".join(m.content for m in conv.messages[:5] if m.content),
        max_kw=5,
    )
    kw_str = ", ".join(keywords) if keywords else "AI, automation, technology"
    return (
        f"In this video, we convert a {conv.source.value} conversation into a narrated breakdown. "
        f"The original chat covers {msg_count} messages about {kw_str}. "
        f"\n\n---\nGenerated by ChatSync + SixBrowse\n"
        f"Source: {conv.source.value} | Conversation: {conv.title}\n"
    )


def _make_tags(conv: Conversation) -> list[str]:
    """Generate YouTube tags."""
    all_text = " ".join(m.content for m in conv.messages[:10] if m.content)
    keywords = _extract_keywords(all_text, max_kw=10)
    base_tags = ["AI", "chatgpt", "conversation", "technology", "tutorial"]
    # Merge, deduplicate, cap at 15.
    seen = set()
    tags = []
    for t in base_tags + keywords:
        tl = t.lower()
        if tl not in seen and len(t) <= 30:
            seen.add(tl)
            tags.append(t)
        if len(tags) >= 15:
            break
    return tags


def _make_thumbnail_suggestion(conv: Conversation) -> str:
    """Suggest a thumbnail concept."""
    first_user = ""
    for m in conv.messages:
        if m.role.value == "user" and m.content.strip():
            first_user = m.content.strip()[:60]
            break
    return (
        f"Split-screen: left side shows the ChatGPT interface with the question "
        f'"{first_user}...", right side shows a bold text overlay with the answer summary. '
        f"Use high-contrast colors (yellow text on dark background) with a surprised/excited facial expression."
    )


def _build_scenes(conv: Conversation) -> list[Scene]:
    """Build timed scenes from conversation messages."""
    scenes: list[Scene] = []
    current_time = 15  # After the 15s hook.

    # Cap at 20 messages for reasonable video length.
    messages = conv.messages[:20]

    for i, msg in enumerate(messages):
        content = (msg.content or "").strip()
        if not content:
            continue

        is_user = msg.role.value == "user"
        duration = _estimate_narration_duration(content)
        start = _format_time(current_time)
        end = _format_time(current_time + duration)

        # Visual description.
        if is_user:
            visual = f"Screen recording of ChatGPT interface. The user's question appears in the chat input box, typed out character by character."
        else:
            visual = f"Animated text overlay on a clean background. Key points from the AI response are highlighted with bullet points appearing one by one."

        # Narration: the actual message content, lightly framed.
        if is_user:
            narration = f"The user asks: {content[:500]}"
        else:
            narration = content[:500]

        # Text overlay: short summary.
        text_overlay = content[:120] + ("..." if len(content) > 120 else "")

        scenes.append(Scene(
            scene_number=i + 1,
            start_time=start,
            end_time=end,
            visual=visual,
            narration=narration,
            text_overlay=text_overlay,
        ))
        current_time += duration

    return scenes


def _make_outro(scenes: list[Scene]) -> str:
    """Generate an outro with call-to-action."""
    return (
        "Thanks for watching! If you found this helpful, hit the like button "
        "and subscribe for more AI conversation breakdowns. Drop a comment below "
        "with your thoughts or questions — what conversation should we cover next?"
    )


def _estimate_total_duration(scenes: list[Scene]) -> str:
    """Estimate total video duration from scenes."""
    if not scenes:
        return "0:30"
    last_end = scenes[-1].end_time
    parts = last_end.split(":")
    total_sec = int(parts[0]) * 60 + int(parts[1]) if len(parts) > 1 else int(parts[0])
    total_sec += 15  # outro
    return _format_time(total_sec)


def generate_youtube_script(conv: Conversation) -> YouTubeScript:
    """Convert a Conversation into a structured YouTube video script.

    Args:
        conv: A Conversation with messages loaded.

    Returns:
        YouTubeScript with timed scenes, hook, description, tags, and outro.

    Raises:
        ValueError: If the conversation has no messages.
    """
    if not conv.messages or len(conv.messages) == 0:
        raise ValueError("Conversation has no messages — cannot generate a script.")

    scenes = _build_scenes(conv)
    if not scenes:
        raise ValueError("No non-empty messages found — cannot generate scenes.")

    return YouTubeScript(
        title=_make_title(conv),
        hook=_make_hook(conv),
        description=_make_description(conv),
        tags=_make_tags(conv),
        source_title=conv.title,
        source=conv.source.value,
        message_count=len(conv.messages),
        estimated_duration=_estimate_total_duration(scenes),
        scenes=scenes,
        outro=_make_outro(scenes),
        thumbnail_suggestion=_make_thumbnail_suggestion(conv),
    )
